spring.application.name=Java_2026FourthStep

# H2 データベース設定
spring.datasource.url=jdbc:h2:mem:logdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2コンソール（ブラウザでDBを確認できる）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console